<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE session [
<!ELEMENT session (committee)*>
<!ELEMENT committee (title, number, subject, date, attendees)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT attendees (senator)*>
<!ELEMENT senator (firstName, lastName)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ATTLIST committee
    type CDATA #REQUIRED>
<!ATTLIST senator
    status CDATA #REQUIRED>
]>

<session>
   <committee type="monetary">
       <title>Finance</title>
       <number>17</number>
       <subject>Donut Costs</subject>
       <date>7/15/2005</date>
       <attendees>
           <senator status="present">
               <firstName>Thomas</firstName>
               <lastName>Smith</lastName>
           </senator>
           <senator status="absent">
               <firstName>Frank</firstName>
               <lastName>McCoy</lastName>
           </senator>
           <senator status="present">
               <firstName>Jay</firstName>
               <lastName>Jones</lastName>
           </senator>
       </attendees>
   </committee>
</session>